### ISSUE TITLE
Crowd funding promotion

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#3]
As space admin who is making a crowd funding, I would like to share dedicated information to motivate investor to look into my project and to invest.

I want to add in [crowd-funding marketplace](https://community.coinsence.org/xcoin/funding-overview) a 
- picture, 
- write my project goals, 
- the usage of funding, 
- links 

and also share information about 
- funding target 
- potential deadline to start the project
- requested currency

ToDo:
- [x] adjust form to add/edit information ( #49 )
- [x] single crowdfunding campaign overview ( #50 )
- [x] design for the crowd funding boxes ( #51 )
- [x] design for the crowd funding boxes within the space ( #52  )

**Comment by SeifBa** [comment]
Where the crowdfunding amount goes ? To the initiator wallet? to the community wallet ?  to the project wallet?
Also, how the the community wallet and project wallet are managed ( collectivly or by the community administrator or delegated persons?

**Comment by KarimChabrak** [comment]
currently the fu ding goes to the funding wallet which is managed by the spade admin. This is always these same wallet which includes the project shares.

We should change that the crowd funding initiator can decide to which wallets the coins goe and we need of course wallets whichcan be collectively managed.

**Comment by bumi** [comment]
@KarimChabrak please add issues for things like "collectively managed wallets" and also for optimizations like deciding which wallets the crowd funding should go to.

**Comment by haythem96** [comment]
> Where the crowdfunding amount goes ? To the initiator wallet? to the community wallet ? to the project wallet?
> Also, how the the community wallet and project wallet are managed ( collectivly or by the community administrator or delegated persons?

I think a community does not have a wallet, as a community is just many peoples in a space

**Comment by haythem96** [comment]
> @KarimChabrak please add issues for things like "collectively managed wallets" and also for optimizations like deciding which wallets the crowd funding should go to.

For that, we can use a MultiSig wallet

**Comment by KarimChabrak** [comment]
@haythem96   Whin spaces there are wallets which are "owned" by the space. Currently only one person can be manager for a wallet. 
In my comment, the word "owned" shall also mean in the future that a community can also manage these wallets. Approve and block accounts, change manager, make transactions....

**Comment by craxrev** [comment]
@KarimChabrak should we bring Malek to this issue, so that he can begin to design crowd funding boxes, or maybe the overall crowd-funding page (or maybe some minor enhancements), Or have you already discussed this with Salem?

**Comment by KarimChabrak** [comment]
@craxrev We can bring Malek to this issue.
We can then discuss together the details.

**Comment by MalekTN** [comment]
Hi guys, okay @KarimChabrak i'll start working on it

**Comment by KarimChabrak** [comment]
@MalekTN 
We could build something like 
https://www.startnext.com/
Check how projects are presented there.

We can use the same structure for crowdsourcing of different challenges.

**Comment by KarimChabrak** [comment]
@MalekTN 

As you can see here, (click also on one of the projects). 
https://www.jovoto.com/projects

The stucture of the crowdsourcing here is quite similar to the structure of the crowd funding in startnext.

**Comment by MalekTN** [comment]
yeah i see, we can make something like this yeah, but once you click on one of the crowdfundings, it should take you to the crowdfunding page(custom page) not the "space " page.

i think we should make a voice call on this one me & you & Salem, there are things that we must clear out before i design it

**Comment by gdalyy** [comment]
@bumi if you agree with what posted karim on trello about the crowdfunding promotion , can we start enhancing this feature ? if yes, @KarimChabrak can we please devide this into more small issues ? I propose that we have the following issues : 
- crowdfunding creation issues ( introduction of new fields ) 
- crowdfunding list view within the space 
- crowdfunding list view accessible via crowdfunding menu button 
- crowdfunding single view 

feel free to decorticate more or to introduce new issue that i maybe forgot

**Comment by bumi** [comment]
you decide! up to you, if you have everything...

**Comment by gdalyy** [comment]
:+1:  @bumi 
@KarimChabrak i need the separate issues

**Comment by KarimChabrak** [comment]
@gdalyy  You can separate issues as you want, 

We have already the crowd funding field in the actuall accounting module.    In the old version, you can create different crowdfunding request in a space (the main difference between different crowd funding initiatives within a space is the requested asset and the rate). 

![image](https://user-images.githubusercontent.com/41925899/54454027-d489b700-4758-11e9-8844-1362a8191cb0.png)

Now for each crowdfunding initiative, the admin shall be able to add additional information (picture, Title, Text, Deadline...) 

*********************

In the old version different requests were shown in the same "card" in the open crowd-funding place. In the next version, they should be shown separate as they could have different contents.... 

![image](https://user-images.githubusercontent.com/41925899/54453891-8eccee80-4758-11e9-9bd9-8b02c9a3ee5a.png)

**Comment by gdalyy** [comment]
@KarimChabrak you didn't understand me well , but i'll create the issues on my own but please check details with me.

**Comment by KarimChabrak** [comment]
@gdalyy 

In the current version, in the details view, I see the first picture twice (ones as a main picture and also in the gallery).   The first picture shall not be shown in the gallery (only as  main picture)

**Comment by KarimChabrak** [comment]
@gdalyy   When clicking on a crowd-funding campain, I would like as user to be directly direct to the detailled description, (not first to the space internal crowd-funding space)
